### ISSUE TITLE
How to add new module

### ISSUE THREAD

**Issue by donkle69** [ex0dus-0x/brute#122]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/brute", line 11, in <module>
    load_entry_point('brute==5.0', 'console_scripts', 'brute')()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/brute-5.0-py3.8.egg/brute/__main__.py", line 115, in main
    path = manager.new_module(modtype, name)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/brute-5.0-py3.8.egg/brute/manager.py", line 146, in new_module
    for temp in os.listdir(templates_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/usr/lib/python3.8/site-packages/brute-5.0-py3.8.egg/brute/modules/templates'
$

**Comment by ex0dus-0x** [comment]
Hey,

`brute/modules/templates` should be the correct path from the base of the egg where templates are being stored for instantiation. Check to see if that directory actually exists in that path and there are files representing the actual templates in there.

I'm assuming that you are attempting to install this on Android or some type of variant due to the irregular filepath where your Python dependencies are installed. You can try using a `virtualenv` in order to better localize your dependencies.

**Comment by 13manveer** [comment]
can you please give me full tutorial on how to use this brute to crack instagram psswords
is this works on instagram??
if it does  please give a full tutorial on what steps does it takes to do so....

i am completely beginner and have problem understanding the readme file  

i dont know how to use and run that.....:-(
